pipeline {
    agent any

    environment {
        IMAGE_NAME = "airist/jenkins-flask-app"
        IMAGE_TAG = "${IMAGE_NAME}:${env.GIT_COMMIT}"
        KUBECONFIG = credentials('kubeconfig-credentials-id')
    }

    stages {

        stage('Setup') {
            steps {
                dir('05-kubernetes') {
                    sh 'chmod 600 $KUBECONFIG'
                    sh "pip install -r requirements.txt"
                }
            }
        }

        stage('Test') {
            steps {
                dir('05-kubernetes') {
                    sh "pytest"
                }
            }
        }

        stage('Login to docker hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-creds',
                                                  usernameVariable: 'USERNAME',
                                                  passwordVariable: 'PASSWORD')]) {
                    sh 'echo ${PASSWORD} | docker login -u ${USERNAME} --password-stdin'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('05-kubernetes') {
                    sh 'docker build -t ${IMAGE_TAG} .'
                    sh 'docker image ls'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push ${IMAGE_TAG}'
            }
        }

        stage('Deploy to Staging') {
            steps {
                sh "kubectl set image deployment/flask-app flask-app=${IMAGE_TAG} -n staging"
            }
        }

        stage('Acceptance Test') {
            steps {
                dir('05-kubernetes') {
                    script {
                        def service = "192.168.88.25:30007"
                        echo "${service}"
                        sh "k6 run -e SERVICE=${service} acceptance-test.js"
                    }
                }
            }
        }

        stage('Deploy to Production') {
            steps {
                sh "kubectl set image deployment/flask-app flask-app=${IMAGE_TAG} -n production"
            }
        }
    }
}
