apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: airist/jenkins-flask-app:68b2cd3062daadb08269ddffd5ec3a5a687e165c
          ports:
            - containerPort: 5000