pipeline {
    agent any

    stages {

        stage('Setup') {
            steps {
                dir('03-lambda-deployment/lambda-app') {
                    sh "pip3 install -r tests/requirements.txt"
                }
            }
        }

        stage('Test') {
            steps {
                dir('03-lambda-deployment/lambda-app') {
                    sh "pytest"
                }
            }
        }

        stage('Build') {
            steps {
                dir('03-lambda-deployment/lambda-app') {
                    sh "sam build -t template.yaml"
                }
            }
        }

        stage('Deploy') {
            environment {
                AWS_ACCESS_KEY_ID = credentials('aws-access-key')
                AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')
            }
            steps {
                dir('03-lambda-deployment/lambda-app') {
                    sh "sam deploy -t template.yaml --no-confirm-changeset --no-fail-on-empty-changeset"
                }
            }
        }
    }
}